# Generated by Django 2.2.5 on 2019-09-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseconfigitem',
            options={'ordering': ['category', 'pk'], 'verbose_name': '基础配置项定义', 'verbose_name_plural': '基础配置项定义'},
        ),
        migrations.AlterField(
            model_name='baseconfigcategory',
            name='content_types',
            field=models.ManyToManyField(blank=True, help_text='使用模型反查时需要填写', to='contenttypes.ContentType', verbose_name='模型类型'),
        ),
    ]
