# Generated by Django 2.2.14 on 2020-08-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0002_auto_20200721_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseconfigvalue',
            options={'ordering': ['item', 'sort_number', '-create_time'], 'verbose_name': '基础配置项值', 'verbose_name_plural': '基础配置项值'},
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='bool_default',
            field=models.BooleanField(blank=True, help_text='布尔值默认值', null=True, verbose_name='布尔值默认值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='choices_source',
            field=models.ForeignKey(blank=True, help_text='选项字段数据源', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseconfig.BaseConfigCategory', verbose_name='选项字段数据源'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='date_default',
            field=models.DateField(blank=True, help_text='日期默认值', null=True, verbose_name='日期默认值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='datetime_default',
            field=models.DateTimeField(blank=True, help_text='日期时间默认值', null=True, verbose_name='日期时间默认值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='decimal_max',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='精确浮点数最大值', max_digits=30, null=True, verbose_name='精确浮点数最大值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='decimal_max_eq',
            field=models.BooleanField(default=False, help_text='精确浮点数最大值包含等于', verbose_name='精确浮点数最大值包含等于'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='decimal_min',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='精确浮点数最小值', max_digits=30, null=True, verbose_name='精确浮点数最小值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='decimal_min_eq',
            field=models.BooleanField(default=False, help_text='精确浮点数最小值包含等于', verbose_name='精确浮点数最小值包含等于'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='float_max',
            field=models.FloatField(blank=True, help_text='浮点数最大值', null=True, verbose_name='浮点数最大值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='float_max_eq',
            field=models.BooleanField(default=False, help_text='浮点数最大值包含等于', verbose_name='浮点数最大值包含等于'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='float_min',
            field=models.FloatField(blank=True, help_text='浮点数最小值', null=True, verbose_name='浮点数最小值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='float_min_eq',
            field=models.BooleanField(default=False, help_text='浮点数最小值包含等于', verbose_name='浮点数最小值包含等于'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='int_max',
            field=models.IntegerField(blank=True, help_text='整数最大值', null=True, verbose_name='整数最大值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='int_max_eq',
            field=models.BooleanField(default=False, help_text='整数最大值包含等于', verbose_name='整数最大值包含等于'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='int_min',
            field=models.IntegerField(blank=True, help_text='整数最小值', null=True, verbose_name='整数最小值'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='int_min_eq',
            field=models.BooleanField(default=False, help_text='整数最小值包含等于', verbose_name='整数最小值包含等于'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='is_choices',
            field=models.BooleanField(default=False, help_text='是否为选项类型', verbose_name='是否为选项类型'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='is_multiple_choices',
            field=models.BooleanField(default=False, help_text='是否为多选类型', verbose_name='是否为多选类型'),
        ),
        migrations.AddField(
            model_name='baseconfigitem',
            name='time_default',
            field=models.TimeField(blank=True, help_text='时间默认值', null=True, verbose_name='时间默认值'),
        ),
        migrations.AddField(
            model_name='baseconfigvalue',
            name='date_value',
            field=models.DateField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='baseconfigvalue',
            name='datetime_value',
            field=models.DateTimeField(blank=True, null=True, verbose_name='日期时间'),
        ),
        migrations.AddField(
            model_name='baseconfigvalue',
            name='time_value',
            field=models.TimeField(blank=True, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='baseconfigitem',
            name='item_type',
            field=models.CharField(choices=[('str', '字符串'), ('bool', '布尔值'), ('int', '整数'), ('float', '浮点数'), ('decimal', '精确浮点数'), ('date', '日期'), ('datetime', '日期时间'), ('time', '时间')], default='str', max_length=20, verbose_name='配置项类型'),
        ),
    ]
