# Generated by Django 2.2.14 on 2020-08-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0003_auto_20200804_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigvalue',
            name='choices_value',
            field=models.ForeignKey(blank=True, help_text='单选值', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='baseconfig.BaseConfigItem', verbose_name='单选值'),
        ),
        migrations.AddField(
            model_name='baseconfigvalue',
            name='multi_choices_value',
            field=models.ManyToManyField(blank=True, help_text='多选值', null=True, related_name='_baseconfigvalue_multi_choices_value_+', to='baseconfig.BaseConfigItem', verbose_name='多选值'),
        ),
    ]
