# Generated by Django 2.2.14 on 2020-08-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0004_auto_20200811_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconfigvalue',
            name='multi_choices_value',
            field=models.ManyToManyField(blank=True, help_text='多选值', related_name='_baseconfigvalue_multi_choices_value_+', to='baseconfig.BaseConfigItem', verbose_name='多选值'),
        ),
    ]
