# Generated by Django 2.2.14 on 2020-08-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0005_auto_20200811_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigitem',
            name='remark',
            field=models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注'),
        ),
    ]
